/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sdp;

/**
 *
 * @author User
 */
public class AdminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form template
     */
    public AdminMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userListButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dashBoardButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bloodBankButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/iPhone Status bar.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 363, 20);

        jLabel3.setFont(new java.awt.Font("Raleway ExtraBold", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin Page");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 30, 170, 43);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/adminmainmenu.png"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 80, 250, 220);

        userListButton.setFont(new java.awt.Font("Raleway ExtraBold", 1, 17)); // NOI18N
        userListButton.setForeground(new java.awt.Color(222, 10, 30));
        userListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/adminuserlist.png"))); // NOI18N
        userListButton.setText("View Users List                         ");
        userListButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 10, 30), 2));
        userListButton.setPreferredSize(new java.awt.Dimension(266, 60));
        userListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userListButtonActionPerformed(evt);
            }
        });
        jPanel2.add(userListButton);
        userListButton.setBounds(40, 320, 300, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/Ellipse 24.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 375, 320);

        dashBoardButton.setFont(new java.awt.Font("Raleway ExtraBold", 1, 17)); // NOI18N
        dashBoardButton.setForeground(new java.awt.Color(222, 10, 30));
        dashBoardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/admindashboard.png"))); // NOI18N
        dashBoardButton.setText("Data Dashboard                       ");
        dashBoardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 10, 30), 2));
        dashBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBoardButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dashBoardButton);
        dashBoardButton.setBounds(40, 520, 300, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/Ellipse 24admin.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 375, 369);

        bloodBankButton.setFont(new java.awt.Font("Raleway ExtraBold", 1, 17)); // NOI18N
        bloodBankButton.setForeground(new java.awt.Color(222, 10, 30));
        bloodBankButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sdp/Images/adminbloodbank.png"))); // NOI18N
        bloodBankButton.setText(" Manage Blood Bank              ");
        bloodBankButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 10, 30), 2));
        bloodBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodBankButtonActionPerformed(evt);
            }
        });
        jPanel2.add(bloodBankButton);
        bloodBankButton.setBounds(40, 420, 300, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloodBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodBankButtonActionPerformed
        new AdminManageBloodBank().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bloodBankButtonActionPerformed

    private void userListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userListButtonActionPerformed
        new ViewUserList().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userListButtonActionPerformed

    private void dashBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBoardButtonActionPerformed
        new BloodCompatibility().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashBoardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloodBankButton;
    private javax.swing.JButton dashBoardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton userListButton;
    // End of variables declaration//GEN-END:variables
}
